[colors]
background = #0b0b0b
background-alt = #141414
foreground = #e6e6e6
primary = #ff4f9a
secondary = #cfa96b
alert = #ff003c
disabled = #6c7086


;;;;;;;;;;;;;;;;;;;;;;
;; MAIN BAR
;;;;;;;;;;;;;;;;;;;;;;

[bar/primary]
width = 100%:-32
height = 30
offset-x = 16
offset-y = 6
radius = 6
line-size = 0
fixed-center = true

override-redirect = true
wm-restack = i3

background = ${colors.background}
foreground = ${colors.foreground}

border-size = 0
border-color = #00000000

padding-left = 2
padding-right = 2
module-margin = 2

separator = ""
separator-foreground = ${colors.disabled}

font-0 = JetBrainsMono Nerd Font:size=10;2
font-1 = JetBrainsMono Nerd Font:size=12;2
font-2 = Symbols Nerd Font:size=14;3

modules-left = powermenu spacer-small xworkspaces
modules-center = i3 player spacer 
modules-right = brightness pulseaudio battery power-mode memory cpu bluetooth wlan eth xkeyboard date

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true


;;;;;;;;;;;;;;;;;;;;;;
;; WORKSPACES
;;;;;;;;;;;;;;;;;;;;;;


[module/xworkspaces]
type = internal/xworkspaces

enable-click = true
enable-scroll = true
reverse-scroll = true

format = <label-state>

label-active = %name%
label-active-background = ${colors.primary}
label-active-foreground = #0b0b0b
label-active-padding = 3

label-occupied = %name%
label-occupied-foreground = ${colors.foreground}
label-occupied-padding = 2

label-empty = %name%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 2

label-urgent = %name%
label-urgent-foreground = ${colors.primary}
label-urgent-padding = 2


;;;;;;;;;;;;;;;;;;;;;;
;; AUDIO
;;;;;;;;;;;;;;;;;;;;;;

[module/pulseaudio]
type = internal/pulseaudio

format-volume = %{T3}%{T-} <label-volume>
label-volume = %percentage%%

format-muted = %{T3}󰝟%{T-}
format-muted-foreground = ${colors.disabled}

;;;;;;;;;;;;;;;;;;;;;;
;; MEMORY
;;;;;;;;;;;;;;;;;;;;;;

[module/memory]
type = internal/memory
interval = 2

format =  <label>
label = %percentage_used%%


;;;;;;;;;;;;;;;;;;;;;;
;; CPU
;;;;;;;;;;;;;;;;;;;;;;

[module/cpu]
type = internal/cpu
interval = 2

format =  <label>
label = %percentage%%


;;;;;;;;;;;;;;;;;;;;;;
;; NETWORK BASE
;;;;;;;;;;;;;;;;;;;;;;

[network-base]
type = internal/network
interval = 5

format-connected = <label-connected>
format-disconnected = <label-disconnected>

label-disconnected =""


;;;;;;;;;;;;;;;;;;;;;;
;; WIFI
;;;;;;;;;;;;;;;;;;;;;;


[module/wlan]
inherit = network-base
interface-type = wireless

label-connected = %{A1:ronema &:}%{F#ff4f9a} %{F-} %essid%%{A}
label-disconnected = %{A1:ronema &:}%{F#6c7086} %{F-} no wifi%{A}


;;;;;;;;;;;;;;;;;;;;;;
;; ETHERNET
;;;;;;;;;;;;;;;;;;;;;;

[module/eth]
inherit = network-base
interface-type = wired
interface = enp1s0

label-connected = 󰈀  %local_ip%


;;;;;;;;;;;;;;;;;;;;;;
;; KEYBOARD
;;;;;;;;;;;;;;;;;;;;;;

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock

label-layout =  %layout%
label-layout-foreground = ${colors.primary}


;;;;;;;;;;;;;;;;;;;;;;
;; DATE
;;;;;;;;;;;;;;;;;;;;;;

[module/date]
type = internal/date
interval = 1

date =  %H:%M
date-alt = %Y-%m-%d %H:%M:%S

label = %date%
label-foreground = ${colors.primary}


;;;;;;;;;;;;;;;;;;;;;;
;; POWER MENU
;;;;;;;;;;;;;;;;;;;;;;

[module/powermenu]
type = custom/text

format = %{T1} ⏻ %{T-}
content-foreground = ${colors.primary}

click-left = ~/.config/rofi/powermenu.sh



;;;;;;;;;;;;;;;;;;;;;;
;; BATTERY
;;;;;;;;;;;;;;;;;;;;;;


[module/battery]
type = internal/battery

battery = BAT1
adapter = ACAD

poll-interval = 5

format-charging =  <label-charging>
format-charging-foreground = ${colors.primary}

format-discharging = <ramp-capacity> <label-discharging>

format-full =  <label-full>
format-full-foreground = ${colors.primary}

label-charging = %{A1:/home/ice/.config/rofi/power-profile.sh &:}%percentage%%%{A}
label-discharging = %{A1:/home/ice/.config/rofi/power-profile.sh &:}%percentage%%%{A}
label-full = %{A1:/home/ice/.config/rofi/power-profile.sh &:}%percentage%%%{A}

ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 


[module/power-mode]
type = custom/script
exec = ~/.config/polybar/power-mode.sh
interval = 2
click-left = ~/.config/rofi/power-profile.sh


;;;;;;;;;;;;;;;;;;;;;;
;; BRIGHTNESS
;;;;;;;;;;;;;;;;;;;;;;

[module/brightness]
type = internal/backlight

card = intel_backlight

use-actual-brightness = true

enable-scroll = true
scroll-interval = 5

format = <ramp> <label>

label = %percentage%%

ramp-0 = 󰃞
ramp-1 = 󰃟
ramp-2 = 󰃠
ramp-3 = 󰃡


;;;;;;;;;;;;;;;;;;;;;;
;; BLUETOOTH
;;;;;;;;;;;;;;;;;;;;;;

[module/bluetooth]
type = custom/script
interval = 5

exec = bluetoothctl info | grep "Connected: yes" >/dev/null && echo "%{F#ff4f9a}󰂯%{F-}" || echo "󰂲"

click-left = rofi-bluetooth


;;;;;;;;;;;;;;;;;;;;;;
;; WINDOW TITLE
;;;;;;;;;;;;;;;;;;;;;;

[module/xwindow]
type = internal/xwindow
label = %title:0:50:...%



;;;;;;;;;;;;;;;;;;;;;;
;; MEDIA
;;;;;;;;;;;;;;;;;;;;;;

[module/player]
type = custom/script
exec = playerctl metadata --format "󰎆 {{artist}} - {{title}}" 2>/dev/null
exec-if = playerctl status
interval = 2

label = %output%
label-maxlen = 30
label-ellipsis = true

click-left = playerctl play-pause &
click-right = playerctl next &
click-middle = playerctl previous &

scroll-up = playerctl next &
scroll-down = playerctl previous &



;;;;;;;;;;;;;;;;;;;;;;
; LABEL MODE
;;;;;;;;;;;;;;;;;;;;;;

[module/i3]
type = internal/i3

format = <label-mode>

label-mode = 󰩨 %mode%
label-mode-background = ${colors.primary}
label-mode-foreground = ${colors.background}
label-mode-padding = 3


;;;;;;;;;;;;;;;;;;;;;;
;; SPACER
;;;;;;;;;;;;;;;;;;;;;;

[module/spacer]
type = custom/text
content = "          "


[module/spacer-small]
type = custom/text
content = " "


;;;;;;;;;;;;;;;;;;;;;;
;; SETTINGS
;;;;;;;;;;;;;;;;;;;;;;

[settings]
screenchange-reload = true
pseudo-transparency = true
